sudo: false
language: node_js
node_js: node
cache: npm
install:
  - npm install -g now-cli
  - npm install
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: RgfMbxEkN981n6kK/m+0RljypIJH/gzz8JktU47rIKzBvh1KlZhpnxw0BhpCJlXnxcKLmP2pSCPO52YgnRFzt36BgJfQS8vZNNYbqBfHBTFVEPVqhNnHrmZy4Wv4w9xyKhh1/qaopzjjOrtRc43JfdvQAbuFVQfdTxJCSvfy4MCRYSXm2RcPnC2PzPtxTOp8VUWEOIu94P0PK06ybnF+L2nmx7bCnhiHpbMBEVwx3bIgUDvJxlF9eDw4J3baFXc24zNXnsZPQGUflFRrCt2mlU/lPfSczqPd8YhosjHgB41V25cZXiKZnADi2fvGb2L0PNMuu+Q27Y461GjvKFsUkRyn6J9Tac8Jy1wlJkSYx7xSm4sQ+p0+BlY+nS+5XWiuOCV5GmEi/wosKAciQbEl5ojbcTmSC0P5CLDzHQIrK8tgGr5lpwUQJ8BzltEaRsMM1gqLN069FGSyZRGsUTTppdvbRVZfRo2TfCYYwrZtZW1ReAm4D/0h0sahz3YuqODn7ULEToQ2cGBGOgsm0vwJ9ASntVsjBy5rc/0WhggakOEGbhVLNdIo+URnri8c6HCykVEZy/mCPP+0I63EiOx5f98o9w67tDwrliAALAhVLQgInZb9ZFXqAOBwxZ/DsImjk3AFAVmQoip10FLy46K6wj+AP2azT7cRf3/kKdoM77c=
